-- Minimal schema for the assignment.
-- Keep data in hosted PostgreSQL and allow future video support.

create extension if not exists pgcrypto;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.generations (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  type text not null check (type in ('image', 'video')),
  prompt text not null,
  negative_prompt text default '',
  model text not null,
  aspect_ratio text default '16:9',
  resolution text default '1024x1024',
  duration integer default null,
  status text not null default 'queued',
  settings jsonb not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.generation_results (
  id bigint generated by default as identity primary key,
  generation_id bigint not null references public.generations(id) on delete cascade,
  type text not null check (type in ('image', 'video')),
  asset_url text,
  thumbnail_url text,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create index if not exists idx_generations_user_id on public.generations(user_id);
create index if not exists idx_generations_type on public.generations(type);
create index if not exists idx_generation_results_generation_id on public.generation_results(generation_id);

create or replace function public.update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger trigger_generations_updated_at
before update on public.generations
for each row
execute function public.update_updated_at_column();
